[package]
name = "typssg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.7.4"
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
log = "0.4.32"
typst = "0.15.0"
typst-html = "0.15.0"
typst-assets = { version = "0.15.0", features = ["fonts"] }
time = "0.3"

